// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Thread struct {
	ID        uuid.UUID
	RootID    uuid.UUID
	ParentID  uuid.NullUUID
	AuthorID  int32
	CreatedAt time.Time
	Title     sql.NullString
	Content   string
}

type User struct {
	ID        int32
	Username  string
	Password  []byte
	CreatedAt time.Time
}

type Vote struct {
	ID        int32
	VoterID   int32
	ThreadID  uuid.UUID
	Upvote    bool
	CreatedAt time.Time
}
